### ISSUE TITLE
How to modify the LCD code to solve the bug in the ListSelector?  

### ISSUE THREAD

**Issue by amueller80** [aufder/RaspberryPiLcdMenu#1]
Hello,

can you please help me in regards to the following:
"As of this writing, it had a bug, where you need to modify the LCD code to define a blink method, similar to the other cursor methods. Notice there are two noBlinks, so change one to blink and change the code to do the right thing."

Is this bug still valid?
What does this exactly mean?
Which file has to be edited? Adafruit_CharLCDPlate.py? There is only one noBlink method there and one blink.

Thank you and Best Regards,
Armin

**Comment by aufder** [comment]
Hi,
Thanks for alerting me to this.  I haven't looked at the latest
Adafruit_CharLCDPlate.py
in some time.  I will get their latest and update things appropriately.

Yes, at the time, that file had 2 methods named noBlink.

Another modification I made to their files (for my use) was to add a way of
detecting if the lcd plate was present.  I'll look into that as well, and
maybe add comments about that.

Thanks for the interest.
Alan

**Comment by aufder** [comment]
Yup, looking at it now, it appears they fixed the noBlink issue on
12-Mar-2013.  (guess I need to update my Pi too.)

**Comment by aufder** [comment]
Closing this since the Adafruit library was updated to fix the noBlink issue.
