### ISSUE TITLE
LCD Keyboard to enter text

### ISSUE THREAD

**Issue by remrat** [aufder/RaspberryPiLcdMenu#2]
First off, thank you for the great code!  

Second,
would it be possible to add some sort of KeyBoard to your software package?  My Pi gets moved from frequently to different wifi networks, and I need a way to enter the new SSID or Password.  I imagine starting with the first character in the WiFi password, and pressing the "up" key to scroll through the alphabet.  Once the first letter is selected, I could press "right" then begin selecting the second letter.  I think it would be a really useful feature to be added to your code.  I am stumped on how to implement this myself, so I though I would bring the idea to you.

**Comment by aufder** [comment]
Have you looked at ListSelector in the sample code I have there?  It takes a pre-set list of words and allows rapid access by picking a letter at a time.
I think what you want different from that is a way to enter new data a letter at a time.  I have something like that when setting the date/time.  You go up and down a char at a time, but its for digits.  If I do alpha-numeric, people might want the full character set.
I'll give it a try.  Give me a couple days to find time.

**Comment by aufder** [comment]
BTW, have you looked at my functions Use10Network() and UseDHCP()  ?  I use those to switch networks all the time.  You would obviously need to uncomment the commented out command to copy the right interfaces file in place in each function, and build those files up the way you want.
Just a thought.

**Comment by remrat** [comment]
Thanks for the fast reply!!!  Ill look into your thoughts in the morning and report back. 

Again,
Thanks for the great code and a fast reply to my questions.  You have saved countless hours of me troubleshooting and attempting to re-write the wheel...

**Comment by aufder** [comment]
Hey remrat.  I added a new function to get text input from the UI.  Primitive, but works.  You can build your own function, and call GetWord() from your function.  It should return the input text or None if they back out.  See the sample added to the xml config file and try it out.  Limited to ASCII chars 32-127.
Enjoy.
